name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Pre-requisites
        run: sudo apt-get install -y libmariadb-dev python3-dev python3-flask python3-pip
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Running Flask App
        run: |
          export FLASK_APP=main.py
          flask run --port=4830 --host=0.0.0.0
